service: serverless-lambdas-send-emails

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-west-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  SQS_SES_Lambda:
    name: send_mail_via_sqs
    handler: lambda.lambda_handler
    description: Send Emails from sqs events
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"

  SES_Lambda:
    name: send_mail_via_ses
    handler: lambda.lambda_send_email_without_sqs
    description: Send Emails from sqs events
    timeout: 10 # seconds
    memorySize: 256 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"